### ISSUE TITLE
ProteaseGuru does not start

### ISSUE THREAD

**Issue by hcadre** [smith-chem-wisc/ProteaseGuru#26]
Subsequent to downloading and unzipping the latest version of ProteaseGuru on my Windows machine (into an extra folder within programs; 64 bit system, ample memory and processing resources) ProteaseGuru refuses to start: Two short bursts of the activity wheel and then - nothing.... Any suggestions on how to proceed?

**Comment by rmmiller22** [comment]
Do you have .Net Core 3.1 installed on your computer? That would be the first thing I would suggest checking on.

**Comment by hcadre** [comment]
Hi Rachel,

It took me some time to figure out but in the end it turned out that I had to place the ProteaseGuru install NOT into the folder where all other programs are located (labelled "Programme") but somewhere else - literally: desktop, home, D://data....(you name it). Does ProteaseGuru when starting search for particular paths or path names?

Best,

Hannes

________________________________
