### ISSUE TITLE
Portein sequence coverage map is not rendered properly

### ISSUE THREAD

**Issue by hcadre** [smith-chem-wisc/ProteaseGuru#27]
When comparing the cleavage pattern of 2 proteases on any particular protein in the Protein Search menu, the sequence coverage map is not generated properly --> line spacing is not adjusted accordingly to accommodate all fragment lines. This phenomenon mostly (but not completely) disappears when comparing 3 or more enzymes.

![image](https://user-images.githubusercontent.com/16349515/112859133-d6f6a980-90b2-11eb-94e6-46a481249880.png)

**Comment by rmmiller22** [comment]
Thank you for bringing this issue forward. We will work on resolving this error.

**Comment by rmmiller22** [comment]
Hi changes resolving this issue will be incorporated in the upcoming release this week.
