### ISSUE TITLE
Feature request: export sequence coverage map also in .svg or .pdf format

### ISSUE THREAD

**Issue by hcadre** [smith-chem-wisc/ProteaseGuru#28]
Would it be possible to export the sequence coverage map also in .svg or .pdf format? The exported .png file are of very low resolution and not suitable to show to colleagues or collaborators. The screen shot from below is from an exported sequence taken at 500%. 

![image](https://user-images.githubusercontent.com/16349515/112860855-81230100-90b4-11eb-8fc4-4e764e31327e.png)

**Comment by rmmiller22** [comment]
Thank you for the feature request. We will work on accommodating figure export to .svg or .pdf.

**Comment by rmmiller22** [comment]
This issue has been addressed, and will be available in the upcoming release.
