### ISSUE TITLE
PG cannot be opened after adding custom enzyme

### ISSUE THREAD

**Issue by mjfitzhenry** [smith-chem-wisc/ProteaseGuru#29]
If you add a custom enzyme in ProteaseGuru, the program crashes and cannot be open until the proteases.tsv file error is rectified. I found the error was caused by a capital F in Full, which should be all lowercase. It works when the change is corrected.

**Comment by rmmiller22** [comment]
Thank you for bringing your issue forward. I have been unable to recreate this issue. Did you generate the custom protease using the GUI interface or by directly editing the protease.tsv file?

**Comment by mjfitzhenry** [comment]
The custom protease was created through the GUI interface. When you Save Protease, the GUI does not re-open until the protease.tsv file is rectified by directly editing the proteases.tsv file.
[proteases tsv with error.txt](https://github.com/smith-chem-wisc/ProteaseGuru/files/6382531/proteases.tsv.with.error.txt)
[corrected proteases.txt](https://github.com/smith-chem-wisc/ProteaseGuru/files/6382532/corrected.proteases.txt)
[ProteaseGuru error.docx](https://github.com/smith-chem-wisc/ProteaseGuru/files/6382533/ProteaseGuru.error.docx)

**Comment by rmmiller22** [comment]
Thank you for these files. I have changed the code writing to proteases.tsv file, and the issue should be rectified in the upcoming ProteaseGuru release.
