### ISSUE TITLE
Unique peptide reporting

### ISSUE THREAD

**Issue by mchampio3** [smith-chem-wisc/ProteaseGuru#30]
If one imports the same FASTA twice, and renames it <Ecoli1.fasta> and <Ecoli2.fasta> and performs Protease Guru, shouldn't the "Number of Peptide Sequences Found only in Ecoli1.fasta and E coli2.fasta  = 0 ?  When I run this, it is returning an answer equal to the number of unique peptides for each database.  It doesn't seem to be making the cross-fasta comparison correctly
![Eco_eco](https://user-images.githubusercontent.com/82989142/115646851-e69f9180-a2f0-11eb-8dd5-a102cbf96902.png)
[Eco_ecop.pdf](https://github.com/smith-chem-wisc/ProteaseGuru/files/6355087/Eco_ecop.pdf)

Am I misunderstanding what this value is reporting?

**Comment by rmmiller22** [comment]
Hi, thank you for bringing this issue to my attention. There is a bug in the generation of the results. This issue will be resolved in the upcoming release this week.

**Comment by rmmiller22** [comment]
It is a specific issue to running the same database twice within the program.

**Comment by mchampio3** [comment]
I don't think so, If using 2 separate databases, it is there, but repeating
the same one just makes it more obvious.  I named the same database two
different names; so unless it does some sort of checksum on all entries I
don't think it 'knew' they were the same.  (Eg, I didn't load the same
database twice in the program, a repeat load. I made an actual copy and
different name). If this is what you are referring to.

-Matt

**Comment by rmmiller22** [comment]
I have also made a copy of a db to test this issue, so I believe we are doing the same thing. What I found was that if the protein accessions have the same name between the two databases, ProteaseGuru was considering the protein to be identical across databases.

**Comment by mchampio3** [comment]
Ok, thanks Rachel (I assume this is you).

**Comment by rmmiller22** [comment]
No problem! Thanks again for bringing this to my attention. I should have the new release with this all fixed up (amongst other update) out by the end of the week.
